// @ts-nocheck -- skip type checking
import * as docs_7 from "../content/docs/components/progress-bar.mdx?collection=docs&hash=1751658641158"
import * as docs_6 from "../content/docs/components/index.mdx?collection=docs&hash=1751658641158"
import * as docs_5 from "../content/docs/components/illustrations.mdx?collection=docs&hash=1751658641158"
import * as docs_4 from "../content/docs/components/file-upload.mdx?collection=docs&hash=1751658641158"
import * as docs_3 from "../content/docs/components/clickthrough-button.mdx?collection=docs&hash=1751658641158"
import * as docs_2 from "../content/docs/components/button.mdx?collection=docs&hash=1751658641158"
import * as docs_1 from "../content/docs/(root)/index.mdx?collection=docs&hash=1751658641158"
import * as docs_0 from "../content/docs/(root)/about.mdx?collection=docs&hash=1751658641158"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"(root)/about.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/(root)/about.mdx"}, data: docs_0 }, { info: {"path":"(root)/index.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/(root)/index.mdx"}, data: docs_1 }, { info: {"path":"components/button.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/components/button.mdx"}, data: docs_2 }, { info: {"path":"components/clickthrough-button.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/components/clickthrough-button.mdx"}, data: docs_3 }, { info: {"path":"components/file-upload.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/components/file-upload.mdx"}, data: docs_4 }, { info: {"path":"components/illustrations.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/components/illustrations.mdx"}, data: docs_5 }, { info: {"path":"components/index.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/components/index.mdx"}, data: docs_6 }, { info: {"path":"components/progress-bar.mdx","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/components/progress-bar.mdx"}, data: docs_7 }], [{"info":{"path":"meta.json","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/meta.json"},"data":{"pages":["(root)","changelog","components","installation","dark-mode","registry"],"root":true}}, {"info":{"path":"(root)/meta.json","absolutePath":"/home/mta630/Desktop/Projects/Github/mta63089/Repositories/dub-ui/content/docs/(root)/meta.json"},"data":{"title":"Get Started","pages":["index","[Installation](/docs/installation)","components-json","theming","[Dark Mode](/docs/dark-mode)","[CLI](/docs/cli)","monorepo","typography","v0","javascript","blocks","figma","changelog","legacy"]}}])